language: node_js
node_js:
  - "14"

install:
  - npm install
  - npx lerna bootstrap

jobs:
  include:
    - stage: "test"
    - name: "Unit Tests"
      script: npm test -- -- -- --coverage
      after_script:
        - "cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"
    - name: "Lint"
      script: npm run lint
    - name: "Build"
      script: npm run build
    - name: "Check es versions"
      script: npm run test:es:version
    - stage: "Check template"
    - name: "React"
      script: npm run test:release -- react
    - name: "Preact"
      script: npm run test:release -- preact
    - name: "Hyper"
      script: npm run test:release -- hyper
    - name: "uHtml"
      script: npm run test:release -- uhtml
    - name: "Vanilla"
      script: npm run test:release -- vanilla
    - if: tag =~ ^v # Run only for tags
      stage: "deploy"
      script:
        - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
        - npm run release:publish
      skip_cleanup: true